name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker images
        run : |
          docker build -t unbunny/dock:${{ github.sha }} .
          docker push unbunny/dock:{{ guthub.sha }}
    
